# Generated by Django 5.2 on 2025-05-05 12:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('add_on_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_inventory', models.PositiveIntegerField(blank=True, null=True)),
                ('remaining_inventory', models.PositiveIntegerField(blank=True, null=True)),
                ('is_per_person', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Add-On',
                'verbose_name_plural': 'Add-Ons',
                'db_table': 'add_ons',
            },
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(unique=True)),
                ('day_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Event Day',
                'verbose_name_plural': 'Event Days',
                'db_table': 'event_days',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'db_table': 'room_types',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='event.package')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_inventory', models.PositiveIntegerField()),
                ('remaining_inventory', models.PositiveIntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='event.package')),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
                'db_table': 'ticket_types',
            },
        ),
        migrations.CreateModel(
            name='TicketInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_inventory', models.PositiveIntegerField()),
                ('remaining_inventory', models.PositiveIntegerField()),
                ('event_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_inventories', to='event.eventday')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='event.tickettype')),
            ],
            options={
                'verbose_name': 'Ticket Inventory',
                'verbose_name_plural': 'Ticket Inventories',
                'db_table': 'ticket_inventory',
            },
        ),
        migrations.CreateModel(
            name='BookingTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tickets', to='event.booking')),
                ('event_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_tickets', to='event.eventday')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tickets', to='event.tickettype')),
            ],
            options={
                'verbose_name': 'Booking Ticket',
                'verbose_name_plural': 'Booking Tickets',
                'db_table': 'booking_tickets',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='event.tickettype'),
        ),
        migrations.CreateModel(
            name='BookingAddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_add_ons', to='event.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_add_ons', to='event.booking')),
            ],
            options={
                'verbose_name': 'Booking Add-On',
                'verbose_name_plural': 'Booking Add-Ons',
                'db_table': 'booking_add_ons',
                'indexes': [models.Index(fields=['booking'], name='booking_add_booking_8516dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stay_date', models.DateField()),
                ('total_rooms', models.PositiveIntegerField()),
                ('remaining_rooms', models.PositiveIntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_inventories', to='event.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_inventories', to='event.roomtype')),
            ],
            options={
                'verbose_name': 'Room Inventory',
                'verbose_name_plural': 'Room Inventories',
                'db_table': 'room_inventory',
                'indexes': [models.Index(fields=['hotel', 'stay_date'], name='room_invent_hotel_i_3d34ee_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('remaining_rooms__lte', models.F('total_rooms'))), name='room_inventory_remaining_lte_total'), models.CheckConstraint(condition=models.Q(('remaining_rooms__gte', 0)), name='room_inventory_remaining_gte_zero')],
                'unique_together': {('hotel', 'room_type', 'stay_date')},
            },
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stay_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='event.booking')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='event.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='event.roomtype')),
            ],
            options={
                'verbose_name': 'Booking Room',
                'verbose_name_plural': 'Booking Rooms',
                'db_table': 'booking_rooms',
                'indexes': [models.Index(fields=['booking'], name='booking_roo_booking_f0422b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_inventory__lte', models.F('total_inventory'))), name='ticket_type_remaining_inventory_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_inventory__gte', 0)), name='ticket_type_remaining_inventory_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='ticketinventory',
            index=models.Index(fields=['ticket_type', 'event_day'], name='ticket_inve_ticket__af69b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketinventory',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_inventory__lte', models.F('total_inventory'))), name='ticket_inventory_remaining_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='ticketinventory',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_inventory__gte', 0)), name='ticket_inventory_remaining_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='bookingticket',
            index=models.Index(fields=['booking'], name='booking_tic_booking_932518_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['package'], name='bookings_package_df4150_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['ticket_type'], name='bookings_ticket__67ace9_idx'),
        ),
    ]
