# Generated by Django 5.2 on 2025-05-05 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which features are displayed')),
            ],
            options={
                'verbose_name': 'Package Feature',
                'verbose_name_plural': 'Package Features',
                'db_table': 'package_features',
                'ordering': ['package', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='addon',
            constraint=models.CheckConstraint(condition=models.Q(('total_inventory__isnull', True), ('remaining_inventory__lte', models.F('total_inventory')), _connector='OR'), name='add_on_remaining_inventory_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='addon',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_inventory__isnull', True), ('remaining_inventory__gte', 0), _connector='OR'), name='add_on_remaining_inventory_gte_zero'),
        ),
        migrations.AddField(
            model_name='packagefeature',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='event.package'),
        ),
        migrations.AddIndex(
            model_name='packagefeature',
            index=models.Index(fields=['package', 'order'], name='package_fea_package_36a694_idx'),
        ),
    ]
