# Generated by Django 5.2 on 2025-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_packagefeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_hotel_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=10),
        ),
    ]
