# Generated by Django 5.2 on 2025-05-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_package_is_hotel_required_package_starting_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roominventory',
            name='room_invent_hotel_i_3d34ee_idx',
        ),
        migrations.RemoveField(
            model_name='bookingroom',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_premium',
        ),
        migrations.AlterUniqueTogether(
            name='roominventory',
            unique_together={('room_type', 'stay_date')},
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3),
        ),
        migrations.AddIndex(
            model_name='roominventory',
            index=models.Index(fields=['stay_date'], name='room_invent_stay_da_03cb51_idx'),
        ),
        migrations.RemoveField(
            model_name='roominventory',
            name='hotel',
        ),
    ]
