# Generated by Django 5.2 on 2025-05-05 18:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_roominventory_room_invent_hotel_i_3d34ee_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('after_party_type', models.CharField(choices=[('GA', 'General Admission'), ('VIP', 'VIP')], default='GA', max_length=10)),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_capacity', models.PositiveIntegerField()),
                ('remaining_capacity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'After Party',
                'verbose_name_plural': 'After Parties',
                'db_table': 'after_parties',
                'indexes': [models.Index(fields=['event_date', 'after_party_type'], name='after_parti_event_d_fb2cc0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('remaining_capacity__lte', models.F('total_capacity'))), name='after_party_remaining_capacity_lte_total'), models.CheckConstraint(condition=models.Q(('remaining_capacity__gte', 0)), name='after_party_remaining_capacity_gte_zero')],
                'unique_together': {('after_party_type', 'event_date', 'location')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='after_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='event.afterparty'),
        ),
        migrations.CreateModel(
            name='BookingAfterParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('after_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_after_parties', to='event.afterparty')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_after_parties', to='event.booking')),
            ],
            options={
                'verbose_name': 'Booking After Party',
                'verbose_name_plural': 'Booking After Parties',
                'db_table': 'booking_after_parties',
                'indexes': [models.Index(fields=['booking'], name='booking_aft_booking_e4cc27_idx')],
            },
        ),
    ]
