# Generated by Django 5.2 on 2025-05-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_afterparty_booking_after_party_bookingafterparty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tickettype',
            name='ticket_type_remaining_inventory_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='tickettype',
            name='ticket_type_remaining_inventory_gte_zero',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='remaining_inventory',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='total_inventory',
        ),
    ]
