# Generated by Django 5.2 on 2025-05-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_cart_cartitem_cart_carts_user_id_fa2854_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='addon',
            name='add_on_remaining_inventory_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='addon',
            name='add_on_remaining_inventory_gte_zero',
        ),
        migrations.RemoveConstraint(
            model_name='afterparty',
            name='after_party_remaining_capacity_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='afterparty',
            name='after_party_remaining_capacity_gte_zero',
        ),
        migrations.RemoveConstraint(
            model_name='roominventory',
            name='room_inventory_remaining_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='roominventory',
            name='room_inventory_remaining_gte_zero',
        ),
        migrations.RemoveConstraint(
            model_name='ticketinventory',
            name='ticket_inventory_remaining_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='ticketinventory',
            name='ticket_inventory_remaining_gte_zero',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='remaining_inventory',
        ),
        migrations.RemoveField(
            model_name='afterparty',
            name='remaining_capacity',
        ),
        migrations.RemoveField(
            model_name='roominventory',
            name='remaining_rooms',
        ),
        migrations.RemoveField(
            model_name='ticketinventory',
            name='remaining_inventory',
        ),
    ]
