# Generated by Django 5.2 on 2025-05-07 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_addon_add_on_remaining_inventory_lte_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='add_ons/'),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='logging_price_percentage',
            field=models.DecimalField(decimal_places=2, default=0.04, max_digits=10),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='resort_fee_percentage',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=0.16, max_digits=10),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_types/'),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Image',
                'verbose_name_plural': 'Hotel Images',
                'db_table': 'hotel_images',
            },
        ),
    ]
