# Generated by Django 5.2 on 2025-05-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_addon_image_roominventory_logging_price_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='is_standard_hotel_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_transportation_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_vip_after_party_included',
            field=models.BooleanField(default=False),
        ),
    ]
